name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Basket.json" -e "16340986-06c151ab-98cd-4199-8259-71d1140f14c6" --integration-id "151975-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 07af5f61-47fb-4554-8887-917fa0e58f9f --integration-id 151975
